name: Build Container Image

on: push

env:
  IMAGE_NAME: europe-west1-docker.pkg.dev/sw-delivery-shield/containers/python-application

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: read
      packages: write

    outputs:
      digest: ${{ steps.docker-build.outputs.digest }}
      image: ${{ steps.hash.outputs.image_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

    - name: Login to GAR
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # v2.0.0
      with:
        registry: europe-west1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a # v4.0.1
      with:
        images: ${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      id: docker-build
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # v4.0.0
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate hashes
      shell: bash
      id: hash
      run: |
        echo "image_name=${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"


  provenance:
    needs:
      - build-and-push

    permissions:
      actions: read # for detecting the Github Actions environment.
      id-token: write # for creating OIDC tokens for signing.
      packages: write # for uploading attestations.

    if: startsWith(github.ref, 'refs/tags/')
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.5.0

    with:
      image: ${{ needs.build-and-push.outputs.image }}
      digest: ${{ needs.build-and-push.outputs.digest }}
      registry-username: _json_key
      private-repository: true

    secrets:
      registry-password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}


  upload-provenance:
    needs:
      - provenance

    permissions:
      contents: read
      actions: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: provenance
          path: predicate.json
